# Generated by Django 5.1.7 on 2025-05-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteinfo',
            name='nearby_hostels',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
